export const browserCoreExamples = [
  "opnex browser status",
  "opnex browser start",
  "opnex browser start --headless",
  "opnex browser stop",
  "opnex browser tabs",
  "opnex browser open https://example.com",
  "opnex browser focus abcd1234",
  "opnex browser close abcd1234",
  "opnex browser screenshot",
  "opnex browser screenshot --full-page",
  "opnex browser screenshot --ref 12",
  "opnex browser snapshot",
  "opnex browser snapshot --format aria --limit 200",
  "opnex browser snapshot --efficient",
  "opnex browser snapshot --labels",
];

export const browserActionExamples = [
  "opnex browser navigate https://example.com",
  "opnex browser resize 1280 720",
  "opnex browser click 12 --double",
  "opnex browser click-coords 120 340",
  'opnex browser type 23 "hello" --submit',
  "opnex browser press Enter",
  "opnex browser hover 44",
  "opnex browser drag 10 11",
  "opnex browser select 9 OptionA OptionB",
  "opnex browser upload /tmp/opnex/uploads/file.pdf",
  'opnex browser fill --fields \'[{"ref":"1","value":"Ada"}]\'',
  "opnex browser dialog --accept",
  'opnex browser wait --text "Done"',
  "opnex browser evaluate --fn '(el) => el.textContent' --ref 7",
  "opnex browser console --level error",
  "opnex browser pdf",
];
